app:
  port: 8080
  version: 1.4

db:
  # host: host.docker.internal #for test with container and container
  host: localhost
  port: 5432
  username: root
  password: P@ssw0rd
  database: user_db

jwt:
  token_secret: "copSecret"
