version: '3.9'
services:
  user_db:
    image: mysql:8.0.30
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=user_db
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
