@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjM0MTUyMzYsImlzcyI6IjEifQ.KVuoxjzFRIG6VMdyU6rVpSs4A8kP2UORzJ2BCiUtGfU
### ping

GET http://localhost:8080/UserService/Ping

### GetAllUser

GET http://localhost:8080/UserService/GetAllUser
Authorization: Bearer {{token}}

### CreateUser

POST  http://localhost:8080/UserService/CreateUser
Content-Type: application/json

{
    "email":"cop1@test.com",
    "password":"1234",
    "name":"cop1"
}

### Login

POST  http://localhost:8080/UserService/Login
Content-Type: application/json

{
    "email":"cop1@test.com",
    "password":"1234"
}

### GetUserProfile

POST  http://localhost:8080/UserService/GetUserProfile
Authorization: Bearer {{token}}

### GetAllUser

GET  http://localhost:8080/UserService/GetAllUser
Authorization: Bearer {{token}}