@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjE4NzEzNjcsImlzcyI6IjIifQ.1rR_T4R9bLNwUVM8J8ZxVBnvjwLMUHzVyse__3--xYw
### ping

GET http://localhost:8080/UserService/ping

### GetAllUser

GET http://localhost:8080/UserService/GetAllUser
Authorization: Bearer {{token}}

### CreateUser

POST  http://localhost:8080/UserApi/CreateUser
Content-Type: application/json

{
    "email":"cop1@test.com",
    "password":"1234",
    "name":"cop1"
}

### Login

POST  http://localhost:8080/UserService/Login
Content-Type: application/json

{
    "email":"cop1@test.com",
    "password":"1234"
}

### GetUserProfile

POST  http://localhost:8080/UserService/GetUserProfile
Authorization: Bearer {{token}}