apiVersion: v1
data:
  db_host: VEJE
  db_port: VEJE
  db_username: VEJE
  db_password: VEJE
  db_database: VEJE
  jwt_secret: VEJE
kind: Secret
metadata:
  name: go-service-butterfly-secret
  namespace: go-service-butterfly
type: Opaque