apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-butterfly
  namespace: go-service-butterfly
  labels:
    customer: cop-customer
    environment: development
    app: go-service-butterfly
spec:
  selector:
    matchLabels:
      app: go-service-butterfly
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-service-butterfly
    spec:
      containers:
        - image: copterbuddy/go-service-butterfly:v1.3
          name: go-service-butterfly
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /Ping
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: go-service-butterfly-secret
                key: db_host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: go-service-butterfly-secret
                key: db_port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: go-service-butterfly-secret
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: go-service-butterfly-secret
                key: db_password
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: go-service-butterfly-secret
                key: db_database
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: go-service-butterfly-secret
                key: jwt_secret
---
apiVersion: v1
kind: Service
metadata:
  name: go-service-butterfly
  namespace: go-service-butterfly
  labels:
    app: go-service-butterfly
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: go-service-butterfly
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-service-butterfly
  namespace: go-service-butterfly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-service-butterfly
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80